### ISSUE TITLE
有些模型文件比较大导致下载时间较长，是否可以增加一个下载的回调函数，以便于通知用户下载的进度？

### ISSUE THREAD

**Issue by airqj** [pyu10055/fetch-wechat#7]
长时间未完成加载模型，有些用户会以为卡住了而直接退出 :)

**Comment by pyu10055** [comment]
@airqj currently fetch does not support progress indicator, this library is to polyfill fetch in wechat. 
TFJS loadGraphModel API has a onPrgrass loadOption, please take a look at the API document.
It allows caller to show progress bar on multiple file models.
https://js.tensorflow.org/api/latest/#loadGraphModel

**Comment by airqj** [comment]
> @airqj currently fetch does not support progress indicator, this library is to polyfill fetch in wechat.
> TFJS loadGraphModel API has a onPrgrass loadOption, please take a look at the API document.
> It allows caller to show progress bar on multiple file models.
> https://js.tensorflow.org/api/latest/#loadGraphModel

thanks
